"""
Download additional real and fake audio samples for testing
Downloads from test dataset and generates synthetic samples
"""

import os
import sys
import shutil
import random
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

def copy_from_test_dataset(samples_dir, num_real=10, num_fake=10):
    """Copy samples from test dataset"""
    print("Copying samples from test dataset...")
    
    test_real_dir = Path("data/audio/test/real")
    test_fake_dir = Path("data/audio/test/fake")
    
    copied_real = 0
    copied_fake = 0
    
    # Copy REAL samples
    if test_real_dir.exists():
        real_files = list(test_real_dir.glob("*.wav"))
        
        if real_files:
            # Get existing count
            existing_real = len(list(samples_dir.glob("real_audio_*.wav")))
            start_idx = existing_real + 1
            
            # Randomly sample
            sample_files = random.sample(real_files, min(num_real, len(real_files)))
            
            for i, src in enumerate(sample_files, start=start_idx):
                dst = samples_dir / f"real_audio_{i}.wav"
                if not dst.exists():
                    shutil.copy2(src, dst)
                    copied_real += 1
                    print(f"  ✓ Copied real_audio_{i}.wav")
    
    # Copy FAKE samples
    if test_fake_dir.exists():
        fake_files = list(test_fake_dir.glob("*.wav"))
        
        if fake_files:
            # Get existing count
            existing_fake = len(list(samples_dir.glob("fake_audio_*.wav")))
            start_idx = existing_fake + 1
            
            # Randomly sample
            sample_files = random.sample(fake_files, min(num_fake, len(fake_files)))
            
            for i, src in enumerate(sample_files, start=start_idx):
                dst = samples_dir / f"fake_audio_{i}.wav"
                if not dst.exists():
                    shutil.copy2(src, dst)
                    copied_fake += 1
                    print(f"  ✓ Copied fake_audio_{i}.wav")
    
    return copied_real, copied_fake

def copy_from_train_dataset(samples_dir, num_real=5, num_fake=5):
    """Copy samples from training dataset"""
    print("\nCopying additional samples from training dataset...")
    
    train_real_dir = Path("data/audio/train/real")
    train_fake_dir = Path("data/audio/train/fake")
    
    copied_real = 0
    copied_fake = 0
    
    # Copy REAL samples
    if train_real_dir.exists():
        real_files = list(train_real_dir.glob("*.wav"))
        
        if real_files:
            # Get existing count
            existing_real = len(list(samples_dir.glob("real_audio_*.wav")))
            start_idx = existing_real + 1
            
            # Randomly sample
            sample_files = random.sample(real_files, min(num_real, len(real_files)))
            
            for i, src in enumerate(sample_files, start=start_idx):
                dst = samples_dir / f"real_audio_{i}.wav"
                if not dst.exists():
                    shutil.copy2(src, dst)
                    copied_real += 1
                    print(f"  ✓ Copied real_audio_{i}.wav (from train)")
    
    # Copy FAKE samples
    if train_fake_dir.exists():
        fake_files = list(train_fake_dir.glob("*.wav"))
        
        if fake_files:
            # Get existing count
            existing_fake = len(list(samples_dir.glob("fake_audio_*.wav")))
            start_idx = existing_fake + 1
            
            # Randomly sample
            sample_files = random.sample(fake_files, min(num_fake, len(fake_files)))
            
            for i, src in enumerate(sample_files, start=start_idx):
                dst = samples_dir / f"fake_audio_{i}.wav"
                if not dst.exists():
                    shutil.copy2(src, dst)
                    copied_fake += 1
                    print(f"  ✓ Copied fake_audio_{i}.wav (from train)")
    
    return copied_real, copied_fake

def generate_synthetic_samples(samples_dir, num_samples=5):
    """Generate synthetic audio samples using TTS"""
    print("\nGenerating synthetic (fake) audio samples...")
    
    try:
        # Try to use pyttsx3 for TTS
        try:
            import pyttsx3
        except ImportError:
            print("  Installing pyttsx3...")
            os.system(f"{sys.executable} -m pip install pyttsx3 -q")
            import pyttsx3
        
        try:
            import scipy.io.wavfile as wavfile
            import numpy as np
        except ImportError:
            print("  Installing scipy...")
            os.system(f"{sys.executable} -m pip install scipy -q")
            import scipy.io.wavfile as wavfile
            import numpy as np
        
        # Sample sentences
        sentences = [
            "This is a synthetic voice generated by text to speech technology.",
            "Artificial intelligence can now create realistic sounding audio.",
            "Voice cloning has become increasingly sophisticated in recent years.",
            "Deepfake audio can be difficult to distinguish from real recordings.",
            "Machine learning models are used to synthesize human speech.",
            "This audio was created entirely by a computer program.",
            "Text to speech systems have improved dramatically.",
            "Synthetic voices are now used in many applications.",
        ]
        
        # Get existing count
        existing_fake = len(list(samples_dir.glob("fake_audio_*.wav")))
        generated = 0
        
        # Initialize TTS engine
        engine = pyttsx3.init()
        engine.setProperty('rate', 150)  # Speed
        
        for i, sentence in enumerate(random.sample(sentences, min(num_samples, len(sentences))), start=existing_fake + 1):
            output_file = samples_dir / f"fake_audio_{i}_synthetic.wav"
            if not output_file.exists():
                try:
                    engine.save_to_file(sentence, str(output_file))
                    engine.runAndWait()
                    
                    if output_file.exists():
                        generated += 1
                        print(f"  ✓ Generated fake_audio_{i}_synthetic.wav")
                except Exception as e:
                    print(f"  ⚠️  Failed to generate sample {i}: {e}")
        
        return generated
        
    except Exception as e:
        print(f"  ⚠️  TTS generation failed: {e}")
        return 0

def main():
    print("="*80)
    print("DOWNLOAD MORE AUDIO SAMPLES FOR TESTING")
    print("="*80)
    
    samples_dir = Path("samples")
    samples_dir.mkdir(exist_ok=True)
    
    # Count existing samples
    existing_real = len(list(samples_dir.glob("real_audio_*.wav")))
    existing_fake = len(list(samples_dir.glob("fake_audio_*.wav")))
    
    print(f"\nCurrent samples: {existing_real} real, {existing_fake} fake")
    
    # Copy from test dataset (priority)
    real_copied_test, fake_copied_test = copy_from_test_dataset(samples_dir, num_real=10, num_fake=10)
    
    # Copy from train dataset if needed
    real_copied_train, fake_copied_train = copy_from_train_dataset(samples_dir, num_real=5, num_fake=5)
    
    # Generate synthetic samples
    synthetic_generated = generate_synthetic_samples(samples_dir, num_samples=5)
    
    # Summary
    total_real_added = real_copied_test + real_copied_train
    total_fake_added = fake_copied_test + fake_copied_train + synthetic_generated
    
    new_real = len(list(samples_dir.glob("real_audio_*.wav")))
    new_fake = len(list(samples_dir.glob("fake_audio_*.wav")))
    
    print("\n" + "="*80)
    print("SUMMARY")
    print("="*80)
    print(f"Added: {total_real_added} real, {total_fake_added} fake samples")
    print(f"  - From test dataset: {real_copied_test} real, {fake_copied_test} fake")
    print(f"  - From train dataset: {real_copied_train} real, {fake_copied_train} fake")
    print(f"  - Synthetic generated: {synthetic_generated} fake")
    print(f"\nTotal samples now: {new_real} real, {new_fake} fake")
    print("="*80)

if __name__ == "__main__":
    main()
