import pyttsx3

engine = pyttsx3.init()

# AI-like voice settings
engine.setProperty('rate', 150)   # Speed of speech
engine.setProperty('volume', 1.0) # Volume (0.0 to 1.0)

text = """
Hello.
I am an artificial intelligence voice.
This audio is generated by a machine learning system.
I do not have emotions.
This is an AI generated speech sample.
"""

engine.save_to_file(text, 'ai_voice.wav')
engine.runAndWait()

print("AI audio file generated: ai_voice.wav")
